### ISSUE TITLE
Current Day not lining up

### ISSUE THREAD

**Issue by raguay** [owenwater/alfred-cal#1]
The header and the days do not line up, but the current day with the star really messes it up. But, this is overall a very cute workflow. Thanks.
![2015-01-01_11-03-14](https://cloud.githubusercontent.com/assets/2487495/5591641/dadbeaa0-91a5-11e4-96d8-7c7896763a02.png)

**Comment by owenwater** [comment]
Hi Richard,

Hmm, it is worse than I think. 

So I updated the workflow which adjusts formatting based on font and font size that Alfred uses. I tried a few fonts and they all work fine. You can download the lastest version from [here](https://github.com/owenwater/alfred-cal/blob/master/Calendar.alfredworkflow?raw=true). Can you please  confirm that does fix the issue?

Regards,
Owen

**Comment by raguay** [comment]
It is better, but the star is off. The numbers are all closer, but not
perfect. Not sure you can without monospaced fonts.[image: Inline image 1]

**Comment by owenwater** [comment]
I don't think it's possible to make it perfect without monospaced fonts. Calculating the width of each character is the best way I can finger out. 

For star, the problem is there is only one character but all the others have two. Let me see if I can find a better solution for it tomorrow. Or just move it to configuration file so it can be easily replaced by anyone who don't like it. :smile:

**Comment by owenwater** [comment]
Hi Richard,

Sorry but I can't find a good solution for star issue. So I add an option in configuration file to switch it off.

Regards,
Owen
